#!/bin/sh
ARCH="x86_64-linux-gnu"

export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/pulseaudio:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/kde4:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/dri:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/qt5/libs:$LD_LIBRARY_PATH"
export QT_PLUGIN_PATH="$SNAP/usr/lib/$ARCH/qt5/plugins"
export XDG_DATA_HOME="$SNAP/usr/share"
export FONTCONFIG_PATH="$SNAP/etc/fonts/config.d"
export FONTCONFIG_FILE="$SNAP/etc/fonts/fonts.conf"
export XKB_CONFIG_ROOT="$SNAP/usr/share/X11/xkb"

export XDG_CONFIG_DIRS="$SNAP/etc/xdg:$XDG_CONFIG_DIRS"
export XDG_CONFIG_DIRS="$SNAP/usr/xdg:$XDG_CONFIG_DIRS"
export XDG_DATA_DIRS="$SNAP_USER_DATA:$XDG_DATA_DIRS"
export XDG_DATA_DIRS="$SNAP/usr/share:$XDG_DATA_DIRS"

exec "$SNAP/usr/bin/krita" $*
