#!/bin/sh
ARCH="x86_64-linux-gnu"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/pulseaudio:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/dri:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$SNAP/usr/lib/$ARCH/qt5/libs:$LD_LIBRARY_PATH"
export QT_PLUGIN_PATH="$SNAP/usr/lib/$ARCH/qt5/plugins"
export XDG_DATA_HOME="$SNAP/usr/share"
export FONTCONFIG_PATH="$SNAP/etc/fonts/config.d"
export FONTCONFIG_FILE="$SNAP/etc/fonts/fonts.conf"
export XKB_CONFIG_ROOT="$SNAP/usr/share/X11/xkb"
export LIBGL_DEBUG="verbose"
#env
launch="$SNAP/usr/games/mame -v -inipath $SNAP $*"
echo "Running following command to launch app:- $launch"

$launch
